exports.refs = {
  entertainment: [
    { description: 'BBC Sounds' },
    { description: 'BBC iPlayer' },
    { description: 'TuneIn' },
    { description: 'Amazon Prime' },
    { description: 'Prime Music' },
    { description: 'Audible' },
    { description: 'Kindle' },
    { description: 'Netflix' },
    { description: 'YouTube' },
    { description: 'Spotify' },
    { description: 'Internet Browser' },
    { description: 'Wikipedia' },
    { description: 'Photos' },
  ],
  diet: [
    { description: 'Breakfast' },
    { description: 'Lunch' },
    { description: 'Dinner' },
    { description: 'Snacks' },
    { description: 'Drinks' },
    { description: 'Sweets' },
    { description: 'Other' },
  ],
  shops: [
    { description: 'Asda' },
    { description: 'Sainsburys' },
    { description: 'Tesco' },
    { description: 'Ocado' },
    { description: 'Waitrose' },
    { description: 'Aldi' },
    { description: 'Lidl' },
    { description: 'Marks and Spencer' },
  ],
  support: [
    { description: 'Trust Mark' },
    { description: 'Age UK' },
    { description: 'NHS' },
    { description: 'Babylon' },
  ],
  yesNo: [{ description: 'Yes' }, { description: 'No' }],
  maritalStatus: [
    { description: 'Married' },
    { description: 'Widow' },
    { description: 'Widower' },
    { description: 'Divorced' },
    { description: 'Civil Partnership' },
  ],
  privileges: [{ description: 'Create' }, { description: 'Edit' }, { description: 'Delete' }],
  hotDrinks: [
    { description: 'Tea' },
    { description: 'Coffee' },
    { description: 'Horlicks' },
    { description: 'Hot chocolate' },
    { description: 'Water' },
    { description: 'Other' },
  ],
  languages: [
    { description: 'English' },
    { description: 'Hindi' },
    { description: 'Mandarin' },
    { description: 'French' },
    { description: 'German' },
  ],
  sports: [
    { description: 'Football' },
    { description: 'Cricket' },
    { description: 'Hockey' },
    { description: 'Tennis' },
    { description: 'Golf' },
    { description: 'Ice Hockey' },
    { description: 'Rowing' },
    { description: 'Rugby' },
    { description: 'Rowing' },
    { description: 'Athletics' },
    { description: 'Swimming' },
    { description: 'Badminton' },
  ],
  colours: [
    { description: 'Blue' },
    { description: 'Red' },
    { description: 'Green' },
    { description: 'Purple' },
    { description: 'Black' },
    { description: 'Orange' },
    { description: 'Yellow' },
    { description: 'Gold' },
    { description: 'White' },
    { description: 'Silver' },
  ],
  accessibility: [
    { description: '1 = very poor access for all, multiple obstacles ' },
    { description: '2 = poor access for someone with limited mobility, steps, stairs, slopes, narrow accessways' },
    { description: '3 = good access for someone with good mobility, may include some steps or stairs' },
    { description: '4 = excellent access for someone with good mobility, no steps, stairs, slope or impediments' },
  ],
  livingConditions: [
    { description: '1 = Living alone' },
    { description: '2 = Living alone but in a communal residence' },
    { description: '3 = Living with others, e.g. partner, spouse, relatives, companion' },
  ],
  geographicIsolation: [
    {
      description:
        '1 = not isolated, suburban location with many close neighbours such as apartment building or semidetached houses',
    },
    { description: '2 = somewhat isolated, suburban with neighbours such as detached house' },
    { description: '3 = moderate isolation, urban location with some distance to closest neighbours' },
    { description: '4 = very isolated, rural location with distant neighbours' },
    {
      description:
        '5 = totally isolated, rural location with very distant neighbours e.g. farms, small holdings, or remote houses.',
    },
  ],
  reminderTypes: [
    { description: 'Medication' },
    { description: 'Appointment' },
    { description: 'Alarm' },
    { description: 'Other' },
  ],
  medicalConditions: [
    { description: 'Diabeties' },
    { description: 'Cancer' },
    { description: 'Haemophelia' },
    { description: 'Rhuematism' },
    { description: 'COPD' },
    { description: 'Stroke' },
    { description: 'Other' },
  ],
  painCommunication: [
    { description: 'Vocalisation' },
    { description: 'Facial expression' },
    { description: 'Physical changes' },
    { description: 'Behavioural change' },
    { description: 'Physiological change' },
    { description: 'Change in Body language' },
  ],
  dental: [
    { description: 'Wears denture' },
    { description: 'Wears dental appliance' },
    { description: 'No dental appliance' },
  ],
  eyewear: [
    { description: 'Wears Glasses' },
    { description: 'Contact Lenses' },
    { description: 'No Glasses or  Contact Lenses' },
  ],
  hearingAid: [
    { description: 'Wears hearing aid' },
    { description: 'Occassionally wears hearing aid' },
    { description: 'No hearing aid' },
  ],
  gender: [{ description: 'Male' }, { description: 'Female' }],
  relationship: [{ description: 'Brother' }, { description: 'Sister' }],
  regularity: [
    { description: 'Always' },
    { description: 'Often' },
    { description: 'Occasionally' },
    { description: 'Never' },
  ],
  gadl: [{ description: '0' }, { description: '1' }, { description: '2' }],
};
