exports.questions = [
  {
    name: 'Loneliness',
    id: 'replace_me',
    description: 'May be self-reported, observations or reported by others in the care circle',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 1,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        description:
          'Never lonely, does not suffer with loneliness or its side effects, actively prefers to be alone, very private by choice',
        value: '1 : Unsuitable',
      },
      {
        description:
          'Some loneliness, occasionally lonely but happy to be alone much of the time, private by choice or circumstance, lonely > daily',
        value: '2 : Unsuitable',
      },
      {
        description: 'Moderate loneliness, feels lonely < daily',
        value: '3 : Suitable',
      },
      {
        description: 'Often lonely multiple times daily, often craves company',
        value: '4 : Suitable',
      },
      {
        description:
          'Very lonely, has physiological impact on daily living, depression, and other ailments attributable',
        value: '5 : Suitable',
      },
    ],
  },
  {
    name: 'Physical mobility',
    id: 'replace_me',
    description: 'May be self-reported, observations or reported by others in the care circle',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 2,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        value: '1 : Unsuitable',
        description: 'Totally immobile with or without mechanical or human assistance (e.g. bed bound)',
      },
      {
        value: '2 : Unsuitable',
        description: 'Some limited mobility with or without mechanical or human assistance',
      },
      {
        value: '3 : Suitable',
        description: 'Moderate mobility with or without mechanical human assistance',
      },
      {
        value: '4 : Suitable',
        description: 'Good mobility with or without mechanical or human assistance',
      },
      {
        value: '5 : Suitable',
        description: 'Full mobility without any assistance',
      },
    ],
  },
  {
    name: 'Geographic isolation',
    id: 'replace_me',
    description: 'May be self-reported, observations or reported by others in the care circle',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 3,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        value: '1 : Suitable',
        description:
          'Not isolated, suburban location with many close neighbours such as apartment building or semidetached houses',
      },
      {
        value: '2 : Suitable',
        description: 'Somewhat isolated, suburban with neighbours such as detached house',
      },
      {
        value: '3 : Suitable',
        description: 'Moderate isolation, urban location with some distance to closest neighbours',
      },
      {
        value: '4 : Suitable',
        description: 'Very isolated, rural location with distant neighbours',
      },
      {
        value: '5 : Suitable',
        description:
          'Totally isolated, rural location with very distant neighbours e.g. farms, small holdings, or remote houses',
      },
    ],
  },
  {
    name: 'Living conditions',
    id: 'replace_me',
    description: '',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 4,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        value: '1 : Suitable',
        description: 'Living alone',
      },
      {
        value: '2 : Suitable',
        description: 'Living alone but in a communal residence',
      },
      {
        value: '3 : Suitable',
        description: 'Living with others, e.g. partner, spouse, relatives, companion',
      },
    ],
  },
  {
    name: 'GADL',
    description: 'May be self-reported, observations or reported by others in the care circle',
    categoryName: 'GADL',
    categoryStatus: '',
    categoryType: 'questions',
    id: 'replace_me',
    type: 'lookup',
    qStatus: '',
    index: 5,
    category: 'suitabilityCriteria',
    subCategory: 'gadl',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'The patient is able to choose and change clothes (dress and undress) by himself/herself',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question:
          'The patient is able to make his/her way to the bathroom, undress, clean him/herself, and dress again',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to use the shower, soap, and bath sponge properly',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to transfer from his/her bed or chair unaided',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to feed himself/herself with tableware',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to do minor household chores',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to use the telephone (make and receive calls)',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to prepare his/her own meals',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to do his/her own washing and ironing',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to manage his/her own money or financial matters',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to run simple errands by himself/herself',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to take his/her medication at the correct dose and time by himself/herself',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'The patient is able to go to distant places by himself/herself using some form of transportation',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'gadl',
        qStatus: '',
        required: 'true',
      },
    ],
  },
  {
    name: 'Social',
    id: 'replace_me',
    description: 'May be self-reported, observations or reported by others in the care circle',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 6,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        value: '1 : Suitable',
        description: 'Very social, sees others regularly (multiple times daily)',
      },
      {
        value: '2 : Suitable',
        description: 'Low isolation, sees others (once daily)',
      },
      {
        value: '3 : Suitable',
        description: 'Moderate isolation, sees others occasionally (weekly) ',
      },
      {
        value: '4 : Suitable',
        description: 'Very isolated, sees others very rarely (monthly or longer)',
      },
      {
        value: '5 : Suitable',
        description: 'Totally isolated, , never sees others',
      },
    ],
  },
  {
    name: 'Technology acceptance',
    id: 'replace_me',
    description: 'May be self-reported, observations or reported by others in the care circle',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 7,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        value: '1 : Suitable',
        description: 'Technophobic, actively avoids technology, finds it frightening or intrusive',
      },
      {
        value: '2 : Suitable',
        description: 'Reluctant, not keen to use technology due to ignorance of benefits or usage, may be persuaded',
      },
      {
        value: '3 : Suitable',
        description: 'Open minded, uses technology when they understand it usefulness and benefits',
      },
      {
        value: '4 : Suitable',
        description:
          'Technophile leaning, used technology regularly and happy to explore new technologies where they are useful',
      },
      {
        value: '5 : Suitable',
        description:
          'Technophile, eagerly seeks out new technologies, happy to experiment, early adopter, advocate to others for technology',
      },
    ],
  },
  {
    name: 'Premises accessibility',
    id: 'replace_me',
    description: '',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 8,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        value: '1 : Suitable',
        description: 'Very poor access for all, multiple obstacles',
      },
      {
        value: '2 : Suitable',
        description: 'Poor access for someone with limited mobility, steps, stairs, slopes, narrow accessways',
      },
      {
        value: '3 : Suitable',
        description: 'Good access for someone with good mobility, may include some steps or stairs',
      },
      {
        value: '4 : Suitable',
        description: 'Excellent access for someone with good mobility, no steps, stairs, slope or impediments',
      },
    ],
  },
  {
    name: 'English proficiency',
    id: 'replace_me',
    description: '',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 9,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    subCategory: '',
    possible_values: [
      {
        value: '1 : Suitable',
        description: 'Poor proficiency in English, not native English speaker',
      },
      {
        value: '2 : Suitable',
        description: 'Good proficiency in English with strong regional accent or speech impediment',
      },
      {
        value: '3 : Suitable',
        description: 'Excellent native English speaker without strong regional accent or speech impediment',
      },
    ],
  },
  {
    id: 'replace_me',
    question: 'Router location',
    answer: '',
    type: 'FreeText',
    qStatus: '',
    required: true,
    lookupList: '',
    category: 'siteSurvey',
    index: 1,
  },
  {
    id: 'replace_me',
    question: 'Master socket location',
    answer: '',
    type: 'FreeText',
    qStatus: '',
    required: false,
    lookupList: '',
    category: 'siteSurvey',
    index: 2,
  },
  {
    id: 'replace_me',
    question: 'Primary ISP',
    answer: '',
    type: 'FreeText',
    qStatus: '',
    required: true,
    lookupList: '',
    category: 'siteSurvey',
    index: 3,
  },
  {
    id: 'replace_me',
    question: 'WiFi cap',
    answer: '',
    type: 'integer',
    qStatus: '',
    required: false,
    lookupList: '',
    category: 'siteSurvey',
    index: 4,
  },
  {
    id: 'replace_me',
    question: 'Is router relocatable?',
    answer: '',
    type: 'Lookup',
    qStatus: '',
    required: false,
    lookupList: '',
    category: 'siteSurvey',
    index: 5,
  },
  {
    id: 'replace_me',
    category: 'siteSurvey',
    qStatus: '',
    categoryName: 'roomWifiAnalysis',
    question: 'Room WiFi Analysis',
    categoryType: 'addFunction',
    categoryAddCount: 8,
    index: 6,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          question: 'Cellular operators in range and signal strength',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: false,
          answerPhoto: '',
          answerNotes: '',
        },
        {
          question: 'Measured WiFi speed (Mb/sec)',
          id: 'replace_me',
          answer: '',
          type: 'Number',
          lookupList: '',
          qStatus: '',
          required: false,
          answerPhoto: '',
          answerNotes: '',
        },
        {
          question: 'Channel/frequency',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: false,
          answerPhoto: '',
          answerNotes: '',
        },
        {
          question: 'Data Delay & Packet Loss %',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: false,
          answerPhoto: '',
          answerNotes: '',
        },
      ],
    },
  },
  {
    question: 'Geographic isolation',
    id: 'replace_me',
    answer: '',
    answerNotes: '',
    type: 'Lookup',
    lookupList: 'geographicIsolation',
    qStatus: '',
    required: 'true',
    index: 7,
    category: 'siteSurvey',
  },
  {
    question: 'Living Conditions',
    id: 'replace_me',
    answer: '',
    answerNotes: '',
    type: 'Lookup',
    lookupList: 'livingConditions',
    qStatus: '',
    required: 'true',
    index: 8,
    category: 'siteSurvey',
  },
  {
    question: 'Premises accessibility ',
    id: 'replace_me',
    answer: '',
    answerNotes: '',
    type: 'Lookup',
    lookupList: 'accessibility',
    qStatus: '',
    required: 'true',
    index: 9,
    category: 'siteSurvey',
  },
  {
    id: 'replace_me',
    index: 1,
    category: 'profile',
    categoryName: 'Identification',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'If applicable, what was your maiden or family name?',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you have any nicknames or names or titles you prefer to be called by?',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What was your date of birth?',
        answer: '',
        type: 'Date',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'Where was your place of birth?',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What is your marital status?',
        answer: '',
        type: 'Lookup',
        lookupList: 'maritalStatus',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What would you like to use as an account password?',
        answer: '',
        type: 'Password',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What is your first language?',
        answer: '',
        type: 'Lookup',
        lookupList: 'language',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Can you speak any other languages?',
        answer: '',
        type: 'Multi',
        lookupList: 'language',
        qStatus: '',
        required: 'false',
        multiPossibleValues: [
          {
            description: 'English',
            selected: '',
          },
          {
            description: 'Hindi',
            selected: '',
          },
          {
            description: 'Mandarin',
            selected: '',
          },
          {
            description: 'French',
            selected: '',
          },
        ],
      },
    ],
  },
  {
    id: 'replace_me',
    index: 2,
    category: 'profile',
    categoryName: 'Family',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 5,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          question: 'Relationship',
          id: 'replace_me',
          answer: '',
          type: 'Lookup',
          lookupList: 'relationship',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Name',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'true',
        },
        {
          question: 'Age',
          id: 'replace_me',
          answer: '',
          type: 'Number',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Gender',
          id: 'replace_me',
          answer: '',
          type: 'Lookup',
          lookupList: 'gender',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Address',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Profession',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
      ],
    },
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 3,
    categoryName: 'Companions',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 5,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          question: 'Privileges',
          id: 'replace_me',
          answer: '',
          type: 'Multi',
          qStatus: '',
          required: 'false',
          multiPossibleValues: [
            {
              description: 'Create',
              selected: '',
            },
            {
              description: 'Edit',
              selected: '',
            },
            {
              description: 'Delete',
              selected: '',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 4,
    categoryName: 'Pets',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Do you have any pets? What breed are they and what is their name(s)?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
    ],
  },

  {
    id: 'replace_me',
    category: 'profile',
    index: 5,
    categoryName: 'Friends',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 5,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          question: 'Where do they live and contact details?',
          id: 'replace_me',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
        {
          id: 'replace_me',
          question: 'How did you meet and how long have you known each other?',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Would you like to designate any of them as companions? If so what privilages should they have?',
          id: 'replace_me',
          answer: '',
          answerNotes: '',
          type: 'Multi',
          qStatus: '',
          required: 'false',
          multiPossibleValues: [
            {
              description: 'Create',
              selected: '',
            },
            {
              description: 'Edit',
              selected: '',
            },
            {
              description: 'Delete',
              selected: '',
            },
          ],
        },
      ],
    },
  },

  {
    id: 'replace_me',
    index: 6,
    category: 'profile',
    categoryName: 'Carers',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 5,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          question: 'Would you like to designate any of them as companions? If so what privilages should they have?',
          id: 'replace_me',
          answer: '',
          answerNotes: '',
          type: 'Multi',
          qStatus: '',
          required: 'false',
          multiPossibleValues: [
            {
              description: 'Create',
              selected: '',
            },
            {
              description: 'Edit',
              selected: '',
            },
            {
              description: 'Delete',
              selected: '',
            },
          ],
        },
        {
          id: 'replace_me',
          question: 'Who is your chemist? Address?',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
        {
          id: '123123809-9901',
          question: 'Who is your dentist? Address?',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
      ],
    },
  },

  {
    id: 'replace_me',
    category: 'profile',
    index: 7,
    categoryName: 'Emergency Contacts Escalation Path',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 5,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          id: 'replace_me',
          question: 'Escalation Number',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'true',
        },
        {
          id: 'replace_me',
          question: 'Additional Notes',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
      ],
    },
  },

  {
    id: 'replace_me',
    category: 'profile',
    index: 8,
    categoryName: 'Additional Emergency Contact Information',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Who is your next of kin?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question:
          'Who is your executor or person with delegated authority or power of attorney in the event of your inability?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question:
          'Do you want to provide your expression of wishes for the record? If so, we will contact you for this information seperately.',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'yesNO',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Who is your GP and what are the surgery details.',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'ICE (In Case of Emergency) box – restricted access – appoint next of kin for ICE info access',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 9,
    categoryName: 'Diet, Allergies & Intolerances',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Do you have any special dietary requirements e.g. vegitarian, non dairy etc ?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'Do you have any food allergies?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'What is your preferred hot drink?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'hotdrinks',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'How does the user take it?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you hydrate (non alchoholic beverages) often? If so how often?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What is your usual eating pattern, snacking all day or regular meals?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'If regular meals, what do you typically have to eat?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you usually cook ?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'regularity',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'If you snack what do you snack on and how often?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you drink alchohol and how often? Are you a social or regular drinker?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 10,
    categoryName: 'Daily Routines',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'What is your usual Morning Routine? Rising, meal times, other activities etc',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'What is your usual Daytime Routine? Meal times, exercise, other activities etc',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'What is your usual Evening Routinue? Bedtime, Reading, other?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you have any problems or need assistance with Washing & Dressing?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you have any problems or need assistance with using the Toilet?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 11,
    categoryName: 'Welfare',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Does the user need any mobility aids? If so, which?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'How is your Eyesight? Do you wear prescription glasses or contact lenses?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'eyewear',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'How is your hearing? Do you use a hearing aid? Is it induction loop ready?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'hearingAid',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question:
          'Which is your best ear for hearing? Do you have any specific problems e.g. tinitus or balance issues?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'How are your Teeth? Do you wear dentures or appliances?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'dental',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you have any specific needs for dental hygiene?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Would you like welfare calls?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'yesNo',
        qStatus: '',
        required: 'false',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 12,
    categoryName: 'Pain and Wellbeing',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'How does the user communicate pain and discomfort?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'painCommunication',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'How does this present?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What is most upsetting for the user?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 13,
    categoryName: 'Long term health',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Does the user have any chronic conditions?',
        answer: '',
        answerNotes: '',
        type: 'Multi',
        qStatus: '',
        required: 'true',
        multiPossibleValues: [
          {
            description: 'Diabeties',
            selected: '',
          },
          {
            description: 'Cancer',
            selected: '',
          },
          {
            description: 'Haemophelia',
            selected: '',
          },
        ],
      },
      {
        id: 'replace_me',
        question: 'How are these managed?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question:
          'Any other conditions that affect the users life style significantly such as Asthma, Eczema, Persistant pains',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What medications do you regularly take for the above conditions?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Have you had any falls in the past and what caused them?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'Have you had any UTIs in the past?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 14,
    categoryName: 'Medication Times',
    categoryStatus: '',
    categoryAddCount: 5,
    categoryType: 'addFunction',
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          id: 'replace_me',
          question: 'Medication Time',
          answer: '',
          answerNotes: '',
          type: 'Time',
          lookupList: '',
          qStatus: '',
          required: 'true',
        },
        {
          id: 'replace_me',
          question: 'Additional Notes',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
      ],
    },
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 15,
    categoryName: 'Reminders',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 5,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          id: 'replace_me',
          question: 'Reminder Time',
          answer: '',
          answerNotes: '',
          type: 'Time',
          lookupList: '',
          qStatus: '',
          required: 'true',
        },
        {
          id: 'replace_me',
          question: 'Additional Notes',
          answer: '',
          answerNotes: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
      ],
    },
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 16,
    categoryName: 'Accounts',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Entertainment?',
        answer: '',
        answerNotes: '',
        type: 'Multi',
        qStatus: '',
        required: 'false',
        multiPossibleValues: [
          {
            description: 'BBC Sounds',
            selected: '',
          },
          {
            description: 'BBC iPLayer',
            selected: '',
          },
          {
            description: 'Tunein',
            selected: '',
          },
          {
            description: 'Prime Amazon',
            selected: '',
          },
        ],
      },
      {
        id: 'replace_me',
        question: 'Shopping?',
        answer: '',
        answerNotes: '',
        type: 'Multi',
        qStatus: '',
        required: 'false',
        multiPossibleValues: [
          {
            description: 'Morrisons',
            selected: '',
          },
          {
            description: 'Sainsburys',
            selected: '',
          },
          {
            description: 'Tesco',
            selected: '',
          },
          {
            description: 'Ocado',
            selected: '',
          },
        ],
      },
      {
        id: 'replace_me',
        question: 'Support?',
        answer: '',
        answerNotes: '',
        type: 'Multi',
        qStatus: '',
        required: 'false',
        multiPossibleValues: [
          {
            description: 'Trust Mark',
            selected: '',
          },
          {
            description: 'Age UK',
            selected: '',
          },
          {
            description: 'NHS',
            selected: '',
          },
          {
            description: 'Babylon',
            selected: '',
          },
        ],
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 17,
    categoryName: 'Favourite things',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Favourite colour?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'colours',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'Favourite sport?',
        answer: '',
        answerNotes: '',
        type: 'Lookup',
        lookupList: 'sports',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'Favourite film?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 18,
    categoryName: 'Important people',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'Important people from the past?',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
    ],
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 19,
    categoryName: 'Reminiscence',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'how did you meet your spouse? (if applicable)',
        answer: '',
        answerNotes: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
    ],
  },
];
