exports.questions = [
  {
    name: 'Loneliness',
    id: 'replace_me',
    description: 'May be self-reported, observations or reported by others in the care circle',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 1,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    possible_values: [
      {
        description:
          'Never lonely, does not suffer with loneliness or its side effects, actively prefers to be alone, very private by choice',
        value: '1 : Unsuitable',
      },
      {
        description:
          'Some loneliness, occasionally lonely but happy to be alone much of the time, private by choice or circumstance, lonely > daily',
        value: '2 : Unsuitable',
      },
      {
        description: 'Moderate loneliness, feels lonely < daily',
        value: '3 : Suitable',
      },
      {
        description: 'Often lonely multiple times daily, often craves company',
        value: '4 : Suitable',
      },
      {
        description:
          'Very lonely, has physiological impact on daily living, depression, and other ailments attributable',
        value: '5 : Suitable',
      },
    ],
  },
  {
    name: 'Physical mobility',
    id: 'replace_me',
    description: 'May be self-reported, observations or reported by others in the care circle',
    answer: '',
    type: 'lookup',
    qStatus: '',
    required: true,
    index: 2,
    answerTime: '',
    answerLat: '',
    answerLong: '',
    category: 'suitabilityCriteria',
    possible_values: [
      {
        value: '1 : Unsuitable',
        description: 'Totally immobile with or without mechanical or human assistance (e.g. bed bound)',
      },
      {
        value: '2 : Unsuitable',
        description: 'Some limited mobility with or without mechanical or human assistance',
      },
      {
        value: '3 : Suitable',
        description: 'Moderate mobility with or without mechanical human assistance',
      },
      {
        value: '4 : Suitable',
        description: 'Good mobility with or without mechanical or human assistance',
      },
      {
        value: '5 : Suitable',
        description: 'Full mobility without any assistance',
      },
    ],
  },
  {
    id: 'replace_me',
    question: 'Router location',
    answer: '',
    type: 'FreeText',
    qStatus: '',
    required: true,
    lookupList: '',
    category: 'siteSurvey',
    index: 1,
  },
  {
    id: 'replace_me',
    question: 'Master socket location',
    answer: '',
    type: 'FreeText',
    qStatus: '',
    required: false,
    lookupList: '',
    category: 'siteSurvey',
    index: 2,
  },
  {
    id: 'replace_me',
    question: 'Primary ISP',
    answer: '',
    type: 'FreeText',
    qStatus: '',
    required: true,
    lookupList: '',
    category: 'siteSurvey',
    index: 3,
  },
  {
    id: 'replace_me',
    question: 'WiFi cap',
    answer: '',
    type: 'integer',
    qStatus: '',
    required: false,
    lookupList: '',
    category: 'siteSurvey',
    index: 4,
  },
  {
    id: 'replace_me',
    question: 'Is router relocatable?',
    answer: '',
    type: 'Lookup',
    qStatus: '',
    required: false,
    lookupList: '',
    category: 'siteSurvey',
    index: 5,
  },
  {
    id: 'replace_me',
    roomName: '',
    roomStatus: '',
    category: 'roomWifiAnalysis',
    index: 1,
    roomQuestions: [
      {
        question: 'Cellular operators in range and signal strength',
        id: 'replace_me',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: false,
      },
      {
        question: 'Measured WiFi speed (Mb/sec)',
        id: 'replace_me',
        answer: '',
        type: 'Number',
        lookupList: '',
        qStatus: '',
        required: false,
      },
      {
        question: 'Channel/frequency',
        id: 'replace_me',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: false,
      },
      {
        question: 'Data Delay & Packet Loss %',
        id: 'replace_me',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: false,
      },
    ],
  },
  {
    id: 'replace_me',
    roomName: '',
    roomStatus: '',
    category: 'roomWifiAnalysis',
    index: 2,
    roomQuestions: [
      {
        question: 'Cellular operators in range and signal strength',
        id: 'replace_me',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: false,
      },
      {
        question: 'Measured WiFi speed (Mb/sec)',
        id: 'replace_me',
        answer: '',
        type: 'Number',
        lookupList: '',
        qStatus: '',
        required: false,
      },
      {
        question: 'Channel/frequency',
        id: 'replace_me',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: false,
      },
      {
        question: 'Data Delay & Packet Loss %',
        id: 'replace_me',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: false,
      },
    ],
  },
  {
    id: 'replace_me',
    index: 1,
    category: 'profile',
    categoryName: 'Identification',
    categoryStatus: '',
    categoryType: 'questions',
    categoryQuestions: [
      {
        id: 'replace_me',
        question: 'If applicable, what was your maiden or family name?',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Do you have any nicknames or names or titles you prefer to be called  by?',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What was your Date of Birth?',
        answer: '',
        type: 'Date',
        lookupList: '',
        qStatus: '',
        required: 'true',
      },
      {
        id: 'replace_me',
        question: 'Where was your Place of birth?',
        answer: '',
        type: 'FreeText',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Marital status?',
        answer: '',
        type: 'Lookup',
        lookupList: 'maritalStatus',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What would you like to use as an account password?',
        answer: '',
        type: 'Password',
        lookupList: '',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'What is your first language?',
        answer: '',
        type: 'Lookup',
        lookupList: 'language',
        qStatus: '',
        required: 'false',
      },
      {
        id: 'replace_me',
        question: 'Can you speak any other languages?',
        answer: '',
        type: 'Multi',
        lookupList: 'language',
        qStatus: '',
        required: 'false',
      },
    ],
  },
  {
    id: 'replace_me',
    index: 2,
    category: 'profile',
    categoryName: 'Family',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 10,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          question: 'Relationship',
          id: 'replace_me',
          answer: '',
          type: 'Lookup',
          lookupList: 'relationship',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Name',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'true',
        },
        {
          question: 'Age',
          id: 'replace_me',
          answer: '',
          type: 'Number',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Gender',
          id: 'replace_me',
          answer: '',
          type: 'Lookup',
          lookupList: 'gender',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Address',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
        {
          question: 'Profession',
          id: 'replace_me',
          answer: '',
          type: 'FreeText',
          lookupList: '',
          qStatus: '',
          required: 'false',
        },
      ],
    },
  },
  {
    id: 'replace_me',
    category: 'profile',
    index: 3,
    categoryName: 'Companions',
    categoryStatus: '',
    categoryType: 'addFunction',
    categoryAddCount: 6,
    categoryAddData: {
      id: 'replace_me',
      catAddName: '',
      catAddStatus: '',
      catAddQuestions: [
        {
          question: 'Privileges',
          id: 'replace_me',
          answer: '',
          type: 'Lookup',
          lookupList: 'privileges',
          qStatus: '',
          required: 'false',
        },
      ],
    },
  },
];
